# Generated by Django 5.2.9 on 2026-04-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.IntegerField(unique=True)),
                ('d_name', models.CharField(choices=[('civil', 'CIVIL'), ('csc', 'CSC'), ('ece', 'ECE'), ('mech', 'MECH')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(unique=True)),
                ('s_name', models.CharField(max_length=100)),
                ('s_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.IntegerField(unique=True)),
                ('f_name', models.CharField(max_length=40)),
                ('f_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.department')),
            ],
        ),
    ]
